services:
  web:
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./custom-addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: --config=/etc/odoo/odoo.conf
    networks:
      - odoo-net

  db:
    image: ${DB_IMAGE}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-net
    command: postgres -c listen_addresses='*'

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-net:
